import type { Env } from './env';

/** Every key this application uses in R2, in one place. */
export const keys = {
  siteConfig: 'configuration/site.json',
  invite: 'configuration/invite.json',
  memoriesIndex: 'index/memories.json',
  photosIndex: 'index/photos.json',
  memory: (id: string) => `memories/${id}.json`,
  photoMetadata: (id: string) => `metadata/photos/${id}.json`,
  photoOriginal: (id: string, extension: string) => `photos/originals/${id}.${extension}`,
  photoThumbnail: (id: string) => `photos/thumbnails/${id}.jpg`,
} as const;

/**
 * Identifiers are generated by the Worker, but they arrive back from the
 * browser in URLs, so they are checked before being used to build a key.
 * Without this a request for `../../configuration/site` would be a path
 * traversal into another part of the bucket.
 */
export function isSafeId(id: string): boolean {
  return /^[a-z0-9][a-z0-9-]{0,63}$/.test(id);
}

/** Reads and parses a JSON object, returning null when it does not exist. */
export async function readJson<T>(env: Env, key: string): Promise<T | null> {
  const object = await env.BUCKET.get(key);
  if (object === null) return null;

  try {
    return (await object.json()) as T;
  } catch {
    // A corrupt object should not take the whole site down; the caller falls
    // back to its default and the problem is visible in the logs.
    console.error(`Could not parse JSON stored at ${key}`);
    return null;
  }
}
